// 弹窗
export const FRONT_LAYER_POPUP_COMPONENT = 'FRONT_LAYER_POPUP_COMPONENT';

export const FRONT_LAYER_ROLL_COMPONENT = 'FRONT_LAYER_ROLL_COMPONENT';

export const CONFIG_CURRENT_MODULE = 'CONFIG_CURRENT_MODULE';

export const TOP_ROLL_COMPONENT = 'TOP_ROLL_COMPONENT';

export const TOP_ROLL_COMPONENT_COMPLETE = 'TOP_ROLL_COMPONENT_COMPLETE';

export const SCROLL_TOP_LINE = 'SCROLL_TOP_LINE';
